services:
    xi_sms.gateway:
        class: Xi\Sms\SmsService
        arguments: [ "@xi_sms.gateway.inner" ]

    xi_sms.filter.number_limiter:
        class: Xi\Sms\Filter\NumberLimitingFilter
        arguments: []
        tags:
            -  { name: xi_sms.filter }
